#!/usr/bin/env php
<?php

// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
//umask(0000);

set_time_limit(0);

require_once __DIR__.'/bootstrap.php.cache';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;
use josegonzalez\Dotenv\Loader as DotenvLoader;

DotenvLoader::load([
    'filepath'  => __DIR__ . '/../.env',
    'putenv'    => true,
    'toEnv'     => true,
    'toServer'  => true,
]);

if ((bool) $_SERVER['SYMFONY_DEBUG']) {
    Debug::enable();
}

$input = new ArgvInput();
$kernel = new AppKernel($_SERVER['SYMFONY_ENV'], (bool) $_SERVER['SYMFONY_DEBUG']);
$application = new Application($kernel);
$application->run($input);
